customer/urls.py
from django.urls import path
from .views import CustomerRegistrationView, CustomerProfileView, CustomerProfileUpdateView, CustomerProfileDeleteView

urlpatterns = [
    path('signup/', CustomerRegistrationView.as_view(), name='signup-customer'),
    path('profile-info/', CustomerProfileView.as_view(), name='profile-customer'),
    path('profile-info/edit-profile', CustomerProfileUpdateView.as_view(), name='edit-profile-customer'),
    path('profile-info/edit-profile/delete-profile/', CustomerProfileDeleteView.as_view(), name='delete_profile_customer'),
]

potentialweb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('trainer/', include('trainer.urls')),
    path('customer/', include('customer.urls')),
    path('exercises/', include('exercises.urls')),
    path('routines/', include('routines.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trainer/urls.py
from django.urls import path
from .views import TrainerRegistrationView, TrainerProfileView, TrainerProfileUpdateView, TrainerProfileDeleteView

urlpatterns = [
    path('signup/', TrainerRegistrationView.as_view(), name='signup-trainer'),
    path('profile-info/', TrainerProfileView.as_view(), name='profile-trainer'),
    path('profile-info/edit-profile', TrainerProfileUpdateView.as_view(), name='edit-profile-trainer'),
    path('profile-info/edit-profile/delete-profile/', TrainerProfileDeleteView.as_view(), name='delete_profile_trainer'),
]

customer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from routines.models import Routine

# Create your models here.
class CustomerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    creation_date = models.DateTimeField(default=timezone.now)
    is_premium = models.BooleanField(default=False)
    profile_picture = models.ImageField(upload_to='users/', default='users/user_image.png')
    profile_picture_url = models.URLField(blank=True)
    routines = models.ManyToManyField(Routine, related_name='customers', blank=True)
    
    def __str__(self):
        return self.user.username

customer/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView
from django.views import View
from django.contrib.auth.models import User
from .form import CustomerRegistrationForm, CustomerProfileForm, EditCustomerProfileForm
from . models import CustomerProfile
from django.urls import reverse_lazy
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class CustomerRegistrationView(CreateView):
    template_name = 'customer/signup.html'
    form_class = CustomerRegistrationForm
    success_url = reverse_lazy('home')
    
    
    def form_valid(self, form):

        password = form.cleaned_data['password']
        confirm_password = form.cleaned_data['confirm_password']
        is_premium = form.cleaned_data['is_premium']
        if password != confirm_password:

            return self.render_to_response(self.get_context_data(form=form, password_error='Passwords do not match'))

        username = form.cleaned_data['username']
        user = User.objects.create_user(username=username, password=password)

        customer = CustomerProfile.objects.create(user=user, is_premium=is_premium)
        
        login(self.request, user)

        return redirect(self.success_url)
    
    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        context['password_error'] = form.errors.get('confirm_password')
        return self.render_to_response(context)
    
class CustomerProfileView(View):
    template_name = 'customer/profile_info.html'

    def get(self, request):
        if request.user.is_authenticated and hasattr(request.user, 'customerprofile'):
            profile = request.user.customerprofile
            context = {
                'profile': profile,
                'type': 'customer'
            }
            return render(request, self.template_name, context)
        else:
            return redirect('home')
        
class CustomerProfileUpdateView(UpdateView):
    model = CustomerProfile
    form_class = EditCustomerProfileForm
    template_name = 'customer/edit_profile.html'
    success_url = reverse_lazy('profile-customer')
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        user = self.request.user
        user.username = form.cleaned_data['username']
        user.save()
        return super().form_valid(form)

    def get_object(self, queryset=None):
        return self.request.user.customerprofile
    
class CustomerProfileDeleteView(LoginRequiredMixin, View):
    success_url = reverse_lazy('home')

    def post(self, request, *args, **kwargs):
        user = request.user
        user.delete()
        logout(request)
        return redirect(self.success_url)

templates/customer/edit_profile.html
{% extends '../website/base.html' %}

{% block content %}

<main class="container d-flex flex-column align-items-center">
    <section class="card card-body " style="width: 500px;">
        <h2 class="mb-5 text-center">Edit profile</h2>
        <form class="mb-1" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <div class="form-group d-flex flex-column align-items-center">
                <label for="id_profile_picture">Current Profile Picture</label><br>
                <img src="{{ request.user.customerprofile.profile_picture.url }}" alt="Profile Picture" width="150px" height="150px" class="mb-3 rounded-circle">
            </div>
            {{ form.profile_picture.label_tag }}
            {{ form.profile_picture }}
    
            {{ form.username.label_tag }}
            {{ form.username }}
            {% for error in form.username.errors %}
                <p class="text-danger">{{ error }}</p>
            {% endfor %}
    
            {{ form.description.label_tag }}
            {{ form.description }}
    
            <button type="submit" class="btn btn-primary">Save changes</button>
        </form>
        <button type="button" class="btn btn-danger align-self-start" data-bs-toggle="modal" data-bs-target="#deleteProfileModal">
            Delete profile
        </button>
    </section>
</main>

<div class="modal fade" id="deleteProfileModal" tabindex="-1" aria-labelledby="deleteProfileModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteProfileModalLabel">Confirm Profile Deletion</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete your profile? This action cannot be undone.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <form method="post" action="{% url 'delete_profile_customer' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Yes, delete my profile</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/customer/profile_info.html
{% extends '../website/base.html' %}

{% block content %}

    <main class="container py-5">
        <section class="card card-body d-flex flex-row mb-4">
                <img class="rounded-circle" src="{% if user.trainerprofile %}{{ user.trainerprofile.profile_picture.url }}{% else %}{{ user.customerprofile.profile_picture.url }}{% endif %}" alt="" width='250px' height="250px" alt="">
                <div class="ms-4 mt-1" style="width: 900px;">
                    <h1 class="" style="font-size: 3.5rem; font-weight: 700;">{{user.username}}</h1>
                    {% if user.customerprofile.is_premium == True %}
                        <h4 class="" style="font-weight: 400; color: #2F89F6;">Premium account</h4>
                    {% else %}
                        <h4 class="" style="font-weight: 400;">Simple account</h4>
                    {% endif %}
                    <hr class="mt-2 mb-4">
                    {% if not user.customerprofile.description %}
                        <blockquote class="blockquote text-secondary">
                            <p class="mb-0">You dont have a description about you or your interests</p>
                        </blockquote>
                    {% else %}
                        <blockquote class="blockquote text-secondary" style="white-space: pre-line;">
                            <p>{{user.customerprofile.description}}</p>
                        </blockquote>
                    {% endif %}
                </div>
                <div class="d-flex justify-content-end" style="width: 210px;">
                    <a href="{% url 'edit-profile-customer' %}"><button class="btn btn-dark">Edit profile</button></a>
                </div>
        </section>
        <section class="d-flex justify-content-evenly mt-5">
            <a href="{% url 'routine_list' %}" style="text-decoration: none;"><article class="card card-body d-flex justify-content-center align-items-center bg-opacity-25" style="width: 500px; height: 140px; background-image: url('https://i.pinimg.com/564x/32/f2/72/32f27216482720011061995d6e9880f3.jpg'); background-size: cover; background-position: center;">
                <h3 class="mt-2" style="font-family: Bebas Neue, sans-serif; font-weight: 400; font-style: normal; font-size: 3rem; color: azure;">My routines</h3>
            </article></a>
            <a href="{% url 'exercises-list' %}" style="text-decoration: none;"><article class="card card-body d-flex justify-content-center align-items-center bg-opacity-10" style="width: 500px; height: 140px; background-image: url('https://i.pinimg.com/564x/c9/d3/6e/c9d36e4462e49d12e895bb4613d21cce.jpg'); background-size: cover; background-position: center;">
                <h3 class="mt-2" style="font-family: Bebas Neue, sans-serif; font-weight: 400; font-style: normal; font-size: 3rem; color: azure;">Exercises</h3>
            </article></a>
        </section>
    </main>
    
{% endblock %}

templates/customer/signup.html
{% extends '../website/base.html' %}

{% block content %}

<main class="container d-flex flex-column align-items-center">
    <section class="card card-body " style="width: 500px;">
        <h2 class="mb-5 text-center">Customer profile</h2>
        <form method="post" class="d-flex flex-column">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-dark align-self-center">Register</button>
        </form>
        {% if password_error %}
            <div class="error" style="color: red; margin-top: 10px;">
                {{ password_error }}
            </div>
        {% endif %}
    </section>
</main>
    
{% endblock %}